<a href="https://colab.research.google.com/github/yeb2Binfang/ECE-GY9143HPML/blob/main/Pytorch/2_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch.autograd import Variable

In [2]:
# variable in torch is to build a computational graph
# but this graph is dynamic compared with a static graph in Tensorflow or Theano
# so torch does not have placeholder, torch can just pass vairable to the computational graph
tensor = torch.FloatTensor([[1,2],[3,4]]) # build a tensor
variable = Variable(tensor, requires_grad = True)

In [3]:
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [4]:
# till now, the tensor and variable seem the same
# however, the variable is a part of the graph, it is a part of the auto-gradient
t_out = torch.mean(tensor * tensor) # x^2
v_out = torch.mean(variable * variable) # x^2
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [5]:
v_out.backward() # backpropagation from v_out
# v_out = 1/4 * sum(variable * variable)
# the gradient w.r.t the variable, d(v_out) / d(variable) = 1/4 * 2 * variable = variable / 2
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [8]:
print(variable)
print(variable.data)
print(variable.data.numpy())

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
